### ISSUE TITLE
[Oracle EF] Added Dynamic Filter to existing table

### ISSUE THREAD

**Issue by KennyEng12** [zzzprojects/EntityFramework.DynamicFilters#150] opened 2019-01-08 08:59 UTC
Hi @jcachat @stgelaisalex @jaenyph @JonathanMagnan @waqasm78 ,
I'm using Dynamic Filter for Oracle EF.

I'm having an issue, which is same with #54.
But I don't want to delete all previous migrations and create a new initial migration.

I'm wondering if there any solutions for this issue without delete all previous migrations and create a new initial migration?

Thanks.
Kenny

**Comment by JonathanMagnan** [comment] 2019-01-08 23:32
Hello @KennyEng12 ,

Unfortunately there is no other fix that I know ;(

Best Regards,

Jonathan

**Comment by tom177y** [comment] 2019-01-09 02:47
Hi Jonathan,

It means the only way to resolve this issue is to ensure Dynamic Filter is applied at the time of table creation with reference to #54.

Any plan to rectify this shortcoming for applying Dynamic Filter on existing Oracle tables?

Best regards,
Tommy

**Comment by KennyEng12** [comment] 2019-01-09 05:39
Hi @JonathanMagnan ,

Here is the: [Sample Project](https://drive.google.com/file/d/1vwfTtQ4B301i02Acm92AUisv3BkMs2i3/view?usp=sharing)

I've implemented DynamicFilter in ~/Models/IdentityModels.cs (ApplicationDbContext class).

Thanks,
Kenny

**Comment by KennyEng12** [comment] 2019-01-11 04:12
Thank you @JonathanMagnan ,

Hope can get a solution from you.

Thanks,
Kenny

**Comment by JonathanMagnan** [comment] 2019-01-17 18:12
Hello @tom177y , @KennyEng12 ,

Unfortunately, my developer tried last week and a few hours this week without any progression.

So we will have to abandon it for now until we discover something that could lead us to a solution on this one.

**Comment by KennyEng12** [comment] 2019-01-18 03:03
Hi @JonathanMagnan ,

Thanks for helping us to discover.

So I will leave this OPEN until your team discover something?

Thanks,
Kenny.

**Comment by Worthy7** [comment] 2019-04-22 07:00
Hi everyone, I want to let you know that I have confirmed a bug in Oracle's SQL Generator for EF when using "AlterTableAnnotations" in a migrations. That is the source of this bug and is not related to just EF.DF. (on CreateTable is fine, but another confusing point is that the error for AlterTableAnnotations says `CreateTable` which is wrong)

There is no fix for this right now, I don't actually fully understand what "annotations" are on a table to be honest, I don't understand how it affects anything since no SQL is generated, but, please confirm @JonathanMagnan , I think you can just delete any AlterTableAnnotations from your migrations to keep Oracle quiet.

**Comment by worthy7** [comment] 2021-09-22 04:35
> Hi everyone, I want to let you know that I have confirmed a bug in Oracle's SQL Generator for EF when using "AlterTableAnnotations" in a migrations. That is the source of this bug and is not related to just EF.DF. (on CreateTable is fine, but another confusing point is that the error for AlterTableAnnotations says `CreateTable` which is wrong)
> 
> (proof: https://github.com/Worthy7/OracleTestAlterTableAnnotations)
> 
> There is no fix for this right now, I don't actually fully understand what "annotations" are on a table to be honest, I don't understand how it affects anything since no SQL is generated, but, please confirm @JonathanMagnan , I think you can just delete any AlterTableAnnotations from your migrations to keep Oracle quiet.

just wondering if this ever got answered? After (https://github.com/zzzprojects/EntityFramework.DynamicFilters/issues/153) was fixed I could get migrations generating from initialMigration again, but this annoying problem popped up instead.

I believe the issue is caused by DF trying to do an "AltertableAnnotations", can it somehow be removed without reprecussion?

**Comment by JonathanMagnan** [comment] 2021-09-22 14:10
Hello @worthy7 ,

If there is something, I believe this would be on this line: https://github.com/zzzprojects/EntityFramework.DynamicFilters/blob/master/src/EntityFramework.DynamicFilters.Shared/DynamicFilterConvention.cs#L28

We will look deeper next week

**Comment by worthy7** [comment] 2021-09-23 00:37
Yes I would agree - to b honest it's really oracle's issue but they are
pretty much refusing to fix it (I logged a bug in 2019).
What is this code for? How to annotations help DF?

**Comment by JonathanMagnan** [comment] 2021-09-23 13:18
Will be able to answer you soon ;) I should investigate it at the beginning of next week.

If I don't find any good reason, I will just add an option to allow you to disable this part of the code

**Comment by JonathanMagnan** [comment] 2021-09-23 15:49
Hello @worthy7 ,

The annotation is used to later be able to catch later the filter configuration through the metadata property. For example, here: https://github.com/zzzprojects/EntityFramework.DynamicFilters/blob/master/src/EntityFramework.DynamicFilters.Shared/DynamicFilterQueryVisitorCSpace.cs#L280

So that's pretty much the core logic of how the DF library is working and would be very hard to remove.

Unfortunately, we cannot remove it without repercussion. It will require us way too much code rewrite doing something like this.

Not the answer you wished but at least we now know that doing this request will require too much effort.

**Closed** 2021-09-30 13:12 UTC
